### ISSUE TITLE
NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by yash365** [DaemonLoki/Business-Card-Mail-Extractor#1]
![Screenshot_20190410-132807](https://user-images.githubusercontent.com/25004640/55861918-009c2a80-5b95-11e9-848e-45d1b3b3d64c.png)

**Comment by DaemonLoki** [comment]
Hey @yash365 it seems like you are trying to get an element from an empty array. Could you happen do have more detail where in the code this exception is thrown?
