### ISSUE TITLE
app wont build

### ISSUE THREAD

**Issue by bfmcneill** [DaemonLoki/Business-Card-Mail-Extractor#2]
when i try to build it there is an error saying "registerResGeneratingTask is depricated"

**Comment by DaemonLoki** [comment]
Thanks @bfmcneill for bringing this up.
Which version of Flutter are you on and which operating system?

Also the output of `flutter doctor` might help find out what the issue is.
Thanks already for your input.

**Comment by bfmcneill** [comment]
flutter version: v1.9.1+hotfix.6

I am pretty new to flutter so there is  a good chance the issue is on my end.  I ended up forking the project and making everything jive with my flutter version and android api 28.  Credit for your work has been sited in multiple places in the project. 

https://github.com/bfmcneill/mlkitocr
